type CountryConverter = {}

local countryMap: { [string]: string } = {
  ["AE"] = "United Arab Emirates",
  ["AG"] = "Antigua and Barbuda",
  ["AI"] = "Anguilla",
  ["AL"] = "Albania",
  ["AO"] = "Angola",
  ["AQ"] = "Antarctica",
  ["AR"] = "Argentina",
  ["AS"] = "American Samoa",
  ["AT"] = "Austria",
  ["AU"] = "Australia",
  ["AW"] = "Aruba",
  ["BA"] = "Bosnia and Herzegovina",
  ["BB"] = "Barbados",
  ["BD"] = "Bangladesh",
  ["BE"] = "Belgium",
  ["BG"] = "Bulgaria",
  ["BH"] = "Bahrain",
  ["BJ"] = "Benin",
  ["BL"] = "Saint Barthélemy",
  ["BM"] = "Bermuda",
  ["BN"] = "Brunei Darussalam",
  ["BQ"] = "Bonaire",
  ["BR"] = "Brazil",
  ["BS"] = "Bahamas",
  ["BW"] = "Botswana",
  ["BZ"] = "Belize",
  ["CA"] = "Canada",
  ["CH"] = "Switzerland",
  ["CI"] = "Côte d'Ivoire",
  ["CK"] = "Cook Islands",
  ["CL"] = "Chile",
  ["CM"] = "Cameroon",
  ["CN"] = "China",
  ["CO"] = "Colombia",
  ["CR"] = "Costa Rica",
  ["CU"] = "Cuba",
  ["CV"] = "Cape Verde",
  ["CW"] = "Curaçao",
  ["CY"] = "Cyprus",
  ["CZ"] = "Czech Republic",
  ["DE"] = "Germany",
  ["DJ"] = "Djibouti",
  ["DK"] = "Denmark",
  ["DM"] = "Dominica",
  ["DO"] = "Dominican Republic",
  ["DZ"] = "Algeria",
  ["EC"] = "Ecuador",
  ["EE"] = "Estonia",
  ["EG"] = "Egypt",
  ["EH"] = "Western Sahara",
  ["ES"] = "Spain",
  ["FI"] = "Finland",
  ["FJ"] = "Fiji",
  ["FK"] = "Falkland Islands",
  ["FM"] = "Micronesia",
  ["FO"] = "Faroe Islands",
  ["FR"] = "France",
  ["GB"] = "United Kingdom",
  ["GD"] = "Grenada",
  ["GE"] = "Georgia",
  ["GF"] = "French Guiana",
  ["GG"] = "Guernsey",
  ["GH"] = "Ghana",
  ["GI"] = "Gibraltar",
  ["GL"] = "Greenland",
  ["GM"] = "Gambia",
  ["GP"] = "Guadeloupe",
  ["GQ"] = "Equatorial Guinea",
  ["GR"] = "Greece",
  ["GS"] = "South Georgia & South Sandwich Islands",
  ["GT"] = "Guatemala",
  ["GU"] = "Guam",
  ["GW"] = "Guinea-Bissau",
  ["GY"] = "Guyana",
  ["HK"] = "Hong Kong",
  ["HN"] = "Honduras",
  ["HR"] = "Croatia",
  ["HT"] = "Haiti",
  ["HU"] = "Hungary",
  ["ID"] = "Indonesia",
  ["IE"] = "Ireland",
  ["IL"] = "Israel",
  ["IM"] = "Isle of Man",
  ["IN"] = "India",
  ["IS"] = "Iceland",
  ["IT"] = "Italy",
  ["JE"] = "Jersey",
  ["JM"] = "Jamaica",
  ["JO"] = "Jordan",
  ["JP"] = "Japan",
  ["KE"] = "Kenya",
  ["KH"] = "Cambodia",
  ["KI"] = "Kiribati",
  ["KM"] = "Comoros",
  ["KN"] = "Saint Kitts and Nevis",
  ["KR"] = "South Korea",
  ["KW"] = "Kuwait",
  ["KY"] = "Cayman Islands",
  ["LA"] = "Laos",
  ["LC"] = "Saint Lucia",
  ["LK"] = "Sri Lanka",
  ["LR"] = "Liberia",
  ["LT"] = "Lithuania",
  ["LU"] = "Luxembourg",
  ["LV"] = "Latvia",
  ["LY"] = "Libya",
  ["MA"] = "Morocco",
  ["MC"] = "Monaco",
  ["MD"] = "Moldova",
  ["ME"] = "Montenegro",
  ["MF"] = "Saint Martin (French)",
  ["MG"] = "Madagascar",
  ["MH"] = "Marshall Islands",
  ["MM"] = "Myanmar",
  ["MP"] = "Northern Mariana Islands",
  ["MQ"] = "Martinique",
  ["MS"] = "Montserrat",
  ["MT"] = "Malta",
  ["MU"] = "Mauritius",
  ["MV"] = "Maldives",
  ["MX"] = "Mexico",
  ["MY"] = "Malaysia",
  ["MZ"] = "Mozambique",
  ["NA"] = "Namibia",
  ["NC"] = "New Caledonia",
  ["NF"] = "Norfolk Island",
  ["NG"] = "Nigeria",
  ["NI"] = "Nicaragua",
  ["NL"] = "Netherlands",
  ["NO"] = "Norway",
  ["NU"] = "Niue",
  ["NZ"] = "New Zealand",
  ["OM"] = "Oman",
  ["PA"] = "Panama",
  ["PE"] = "Peru",
  ["PF"] = "French Polynesia",
  ["PG"] = "Papua New Guinea",
  ["PH"] = "Philippines",
  ["PL"] = "Poland",
  ["PM"] = "Saint Pierre and Miquelon",
  ["PN"] = "Pitcairn",
  ["PR"] = "Puerto Rico",
  ["PT"] = "Portugal",
  ["PW"] = "Palau",
  ["QA"] = "Qatar",
  ["RE"] = "Réunion",
  ["RO"] = "Romania",
  ["RS"] = "Serbia",
  ["RU"] = "Russia",
  ["SA"] = "Saudi Arabia",
  ["SB"] = "Solomon Islands",
  ["SC"] = "Seychelles",
  ["SE"] = "Sweden",
  ["SG"] = "Singapore",
  ["SH"] = "Saint Helenians",
  ["SI"] = "Slovenia",
  ["SJ"] = "Svalbard and Jan Mayen",
  ["SK"] = "Slovakia",
  ["SL"] = "Sierra Leone",
  ["SN"] = "Senegal",
  ["SR"] = "Suriname",
  ["ST"] = "Sao Tome and Principe",
  ["SV"] = "El Salvador",
  ["SX"] = "Sint Maarten (Dutch)",
  ["SY"] = "Syria",
  ["TC"] = "Turks and Caicos Islands",
  ["TF"] = "Scattered Islands",
  ["TG"] = "Togo",
  ["TH"] = "Thailand",
  ["TL"] = "Timor-Leste",
  ["TN"] = "Tunisia",
  ["TO"] = "Tonga",
  ["TR"] = "Turkey",
  ["TT"] = "Trinidad and Tobago",
  ["TV"] = "Tuvalu",
  ["TW"] = "Taiwan",
  ["TZ"] = "Tanzania",
  ["UA"] = "Ukraine",
  ["US"] = "United States",
  ["UY"] = "Uruguay",
  ["VC"] = "Saint Vincent and the Grenadines",
  ["VE"] = "Venezuela",
  ["VG"] = "British Virgin Islands",
  ["VI"] = "U.S. Virgin Islands",
  ["VN"] = "Vietnam",
  ["VU"] = "Vanuatu",
  ["WF"] = "Wallis and Futuna",
  ["WS"] = "Samoa",
  ["YE"] = "Yemen",
  ["YT"] = "Mayotte",
  ["ZA"] = "South Africa",
  ["ZW"] = "Zimbabwe",
}

local function convert(self: CountryConverter, input: DataValueString): DataValueString
  local dv: DataValueString = DataValue.string()
  if input and input.value then
    dv.value = countryMap[input.value] or input.value
  else
    dv.value = ""
  end
  return dv
end

local function reverseConvert(self: CountryConverter, input: DataValueString): DataValueString
  local dv: DataValueString = DataValue.string()
  if input and input.value then
    for code, name in pairs(countryMap) do
      if name == input.value then
        dv.value = code
        return dv
      end
    end
    dv.value = input.value
  else
    dv.value = ""
  end
  return dv
end

local function init(self: CountryConverter): boolean
  return true
end

return function(): Converter<CountryConverter, DataValueString, DataValueString>
  return {
    init = init,
    convert = convert,
    reverseConvert = reverseConvert,
  }
end
